// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using USPSimGame.Data;

#nullable disable

namespace USPSimGame.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723161531_Primary")]
    partial class Primary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("USPSimGame.Data.Entities.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CenterLatLong")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentMonth")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Zoom")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.GameSessionMapLayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CachedDataContent")
                        .HasColumnType("text");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MapLayerDefinitionId")
                        .HasColumnType("integer");

                    b.Property<string>("SimulatorTags")
                        .HasColumnType("text");

                    b.Property<string>("TranslatorTags")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("MapLayerDefinitionId");

                    b.ToTable("GameSessionMapLayers");
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.MapLayerDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultStyleConfigJson")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabledByDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LayerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SimulatorTags")
                        .HasColumnType("text");

                    b.Property<string>("TranslatorTags")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MapLayerDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Buildings",
                            Description = "Extruded 3D building footprints derived from 3D BAG lidar elevation data (LoD 1.3).",
                            IsEnabledByDefault = true,
                            Key = "pdok-3dbag-buildings",
                            LayerType = "VectorGeoJson",
                            Name = "3D BAG Buildings (2.5D Extruded)"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Infrastructure",
                            Description = "Electrical grid infrastructure featuring low-, medium-, and high-voltage cables and transformer stations for Liander territory.",
                            IsEnabledByDefault = false,
                            Key = "liander-open-data-elektra",
                            LayerType = "VectorGeoJson",
                            Name = "Liander Electricity Network (Cables & Stations)"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Infrastructure",
                            Description = "Complete low-, medium-, and high-voltage electricity cables and transformer stations for Stedin service territory.",
                            IsEnabledByDefault = false,
                            Key = "stedin-open-data-elektra",
                            LayerType = "VectorGeoJson",
                            Name = "Stedin Regional Electricity Grid"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Infrastructure",
                            Description = "Municipal urban water, sewage pipes, inspection manholes, and pumping stations from Stichting Rioned GWSW.",
                            IsEnabledByDefault = false,
                            Key = "pdok-gwsw-sewage",
                            LayerType = "VectorGeoJson",
                            Name = "Urban Sewage & Drainage Network (PDOK GWSW)"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Environment",
                            Description = "Official municipal boundaries and administrative jurisdiction borders derived from Kadaster BRK.",
                            IsEnabledByDefault = false,
                            Key = "pdok-brk-bestuurlijkegebieden",
                            LayerType = "VectorGeoJson",
                            Name = "Municipal Boundaries (BRK Bestuurlijke Gebieden)"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Environment",
                            Description = "Official cadastral land parcel boundaries, plot sizes, section codes, and parcel numbers from Kadaster BRK.",
                            IsEnabledByDefault = false,
                            Key = "pdok-brk-kadastralekaart",
                            LayerType = "VectorGeoJson",
                            Name = "Cadastral Parcels (BRK Kadastrale Kaart WFS)"
                        });
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.PlayerSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlayerSessions");
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "harald.warmelink@hu.nl",
                            PasswordHash = "",
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.GameSessionMapLayer", b =>
                {
                    b.HasOne("USPSimGame.Data.Entities.GameSession", "GameSession")
                        .WithMany("MapLayers")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("USPSimGame.Data.Entities.MapLayerDefinition", "LayerDefinition")
                        .WithMany()
                        .HasForeignKey("MapLayerDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("LayerDefinition");
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.Team", b =>
                {
                    b.HasOne("USPSimGame.Data.Entities.GameSession", null)
                        .WithMany("Teams")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.GameSession", b =>
                {
                    b.Navigation("MapLayers");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
