// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using USPSimGame.Data;

#nullable disable

namespace USPSimGame.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260729074523_Primary")]
    partial class Primary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("USPSimGame.Data.Entities.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CenterLatLong")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentMonth")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Zoom")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.GameSessionMapLayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CachedDataContent")
                        .HasColumnType("text");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MapLayerDefinitionId")
                        .HasColumnType("integer");

                    b.Property<string>("SimulatorTags")
                        .HasColumnType("text");

                    b.Property<string>("TranslatorTags")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("MapLayerDefinitionId");

                    b.ToTable("GameSessionMapLayers");
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.GameSessionPlannableLayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameSessionId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("PlannableLayerDefinitionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("PlannableLayerDefinitionId");

                    b.ToTable("GameSessionPlannableLayers");
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.MapLayerDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultStyleConfigJson")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabledByDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LayerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SimulatorTags")
                        .HasColumnType("text");

                    b.Property<string>("TranslatorTags")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MapLayerDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Buildings",
                            Description = "3D building footprints, roof shapes, heights, and volumes from 3D BAG (Kadaster/TU Delft).",
                            IsEnabledByDefault = true,
                            Key = "pdok-3dbag-buildings",
                            LayerType = "VectorGeoJson",
                            Name = "3D BAG Buildings"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Infrastructure",
                            Description = "Low-, medium-, and high-voltage electricity grid network for Liander service territory.",
                            IsEnabledByDefault = false,
                            Key = "liander-open-data-elektra",
                            LayerType = "VectorGeoJson",
                            Name = "Liander Electricity Grid"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Infrastructure",
                            Description = "Complete low-, medium-, and high-voltage electricity cables and transformer stations for Stedin service territory.",
                            IsEnabledByDefault = false,
                            Key = "stedin-open-data-elektra",
                            LayerType = "VectorGeoJson",
                            Name = "Stedin Regional Electricity Grid"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Infrastructure",
                            Description = "Municipal urban water, sewage pipes, inspection manholes, and pumping stations from Stichting Rioned GWSW.",
                            IsEnabledByDefault = false,
                            Key = "pdok-gwsw-sewage",
                            LayerType = "VectorGeoJson",
                            Name = "Urban Sewage & Drainage Network (PDOK GWSW)"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Environment",
                            Description = "Official municipal boundaries and administrative jurisdiction borders derived from Kadaster BRK.",
                            IsEnabledByDefault = false,
                            Key = "pdok-brk-bestuurlijkegebieden",
                            LayerType = "VectorGeoJson",
                            Name = "Municipal Boundaries (BRK Bestuurlijke Gebieden)"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Environment",
                            Description = "Official cadastral land parcel boundaries, plot sizes, section codes, and parcel numbers from Kadaster BRK.",
                            IsEnabledByDefault = false,
                            Key = "pdok-brk-kadastralekaart",
                            LayerType = "VectorGeoJson",
                            Name = "Cadastral Parcels (BRK Kadastrale Kaart WFS)"
                        });
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ExpenseDurationMonths")
                        .HasColumnType("integer");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockedBySessionId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StartMonth")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<double>("TotalCalculatedInvestmentPoints")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalCalculatedMonthlyExpensePoints")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("TeamId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.PlanFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameSessionPlannableLayerId")
                        .HasColumnType("integer");

                    b.Property<string>("GeoJsonGeometry")
                        .HasColumnType("text");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<string>("PropertiesJson")
                        .HasColumnType("text");

                    b.Property<string>("TargetFeatureId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionPlannableLayerId");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanFeatures");
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.PlanTeamJudgment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Judgment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("TeamId");

                    b.ToTable("PlanTeamJudgments");
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.PlannableLayerDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultColor")
                        .HasColumnType("text");

                    b.Property<int>("DefaultExpenseDurationMonths")
                        .HasColumnType("integer");

                    b.Property<double?>("DefaultLineWidthPx")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GeometryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<double>("InvestmentPointsPerUnit")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsEnabledByDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("MonthlyExpensePointsPerUnit")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SimulatorTags")
                        .HasColumnType("text");

                    b.Property<string>("TranslatorTags")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlannableLayerDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Infrastructure",
                            DefaultColor = "#f59e0b",
                            DefaultExpenseDurationMonths = 120,
                            DefaultLineWidthPx = 2.5,
                            Description = "Zoned land polygon area designated for ground-mounted solar PV development.",
                            GeometryType = "Polygon",
                            Icon = "bi-sun-fill",
                            InvestmentPointsPerUnit = 30.0,
                            IsEnabledByDefault = true,
                            Key = "solar-farm",
                            MonthlyExpensePointsPerUnit = 1.0,
                            Name = "Solar Farm Area"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Infrastructure",
                            DefaultColor = "#06b6d4",
                            DefaultExpenseDurationMonths = 120,
                            DefaultLineWidthPx = 2.5,
                            Description = "Zoned land polygon area designated for onshore wind turbine installations.",
                            GeometryType = "Polygon",
                            Icon = "bi-wind",
                            InvestmentPointsPerUnit = 30.0,
                            IsEnabledByDefault = true,
                            Key = "wind-farm",
                            MonthlyExpensePointsPerUnit = 1.0,
                            Name = "Wind Farm Zone"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Infrastructure",
                            DefaultColor = "#10b981",
                            DefaultExpenseDurationMonths = 120,
                            DefaultLineWidthPx = 2.0,
                            Description = "Public or commercial electric vehicle charging station hub point location.",
                            GeometryType = "Point",
                            Icon = "bi-ev-station-fill",
                            InvestmentPointsPerUnit = 30.0,
                            IsEnabledByDefault = true,
                            Key = "ev-charger-hub",
                            MonthlyExpensePointsPerUnit = 1.0,
                            Name = "EV Charging Station Hub"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Infrastructure",
                            DefaultColor = "#3b82f6",
                            DefaultExpenseDurationMonths = 120,
                            DefaultLineWidthPx = 3.5,
                            Description = "High, medium, or low voltage power transmission or distribution line.",
                            GeometryType = "Line",
                            Icon = "bi-lightning-charge-fill",
                            InvestmentPointsPerUnit = 30.0,
                            IsEnabledByDefault = true,
                            Key = "power-cable",
                            MonthlyExpensePointsPerUnit = 1.0,
                            Name = "Electricity Connection Cable"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Infrastructure",
                            DefaultColor = "#ef4444",
                            DefaultExpenseDurationMonths = 120,
                            DefaultLineWidthPx = 2.0,
                            Description = "Electrical grid transformer station or substations for voltage step-down/step-up.",
                            GeometryType = "Point",
                            Icon = "bi-box-seam",
                            InvestmentPointsPerUnit = 30.0,
                            IsEnabledByDefault = true,
                            Key = "transformer-substation",
                            MonthlyExpensePointsPerUnit = 1.0,
                            Name = "Transformer Substation"
                        });
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.PlayerSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlayerSessions");
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AnnualBudgetAllowance")
                        .HasColumnType("double precision");

                    b.Property<string>("AreaDefinition")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("integer");

                    b.Property<double>("InvestmentPointsBalance")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockedBySessionId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "harald.warmelink@hu.nl",
                            PasswordHash = "AQAAAAIAAYagAAAAEKstQTVmO/0bmR5/P2B+mTIYP9Ju76yHdGFRYt7uq9Im2XkmV3pwZpvDAMTmlgzY3w==",
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.GameSessionMapLayer", b =>
                {
                    b.HasOne("USPSimGame.Data.Entities.GameSession", "GameSession")
                        .WithMany("MapLayers")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("USPSimGame.Data.Entities.MapLayerDefinition", "LayerDefinition")
                        .WithMany()
                        .HasForeignKey("MapLayerDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("LayerDefinition");
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.GameSessionPlannableLayer", b =>
                {
                    b.HasOne("USPSimGame.Data.Entities.GameSession", "GameSession")
                        .WithMany("PlannableLayers")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("USPSimGame.Data.Entities.PlannableLayerDefinition", "PlannableLayerDefinition")
                        .WithMany()
                        .HasForeignKey("PlannableLayerDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("PlannableLayerDefinition");
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.Plan", b =>
                {
                    b.HasOne("USPSimGame.Data.Entities.GameSession", "GameSession")
                        .WithMany("Plans")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("USPSimGame.Data.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.PlanFeature", b =>
                {
                    b.HasOne("USPSimGame.Data.Entities.GameSessionPlannableLayer", "GameSessionPlannableLayer")
                        .WithMany()
                        .HasForeignKey("GameSessionPlannableLayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("USPSimGame.Data.Entities.Plan", "Plan")
                        .WithMany("Features")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSessionPlannableLayer");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.PlanTeamJudgment", b =>
                {
                    b.HasOne("USPSimGame.Data.Entities.Plan", "Plan")
                        .WithMany("Judgments")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("USPSimGame.Data.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.Team", b =>
                {
                    b.HasOne("USPSimGame.Data.Entities.GameSession", null)
                        .WithMany("Teams")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.GameSession", b =>
                {
                    b.Navigation("MapLayers");

                    b.Navigation("PlannableLayers");

                    b.Navigation("Plans");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("USPSimGame.Data.Entities.Plan", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Judgments");
                });
#pragma warning restore 612, 618
        }
    }
}
